name: Get Sxzb

on:
  schedule:
    - cron: '0 */6 * * *'  # 每 6 小时运行一次
      timezone: Asia/Shanghai  # 设置时区为上海（北京）时间
  workflow_dispatch:  # 手动触发

jobs:
  get_streams:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Create 和 Run Python script
      run: |
        cat > get_iptv.py << 'EOF'
        import requests

        # 定义两个 URL
        urls = [
            "https://tv.wekh.eu.org/sxzb.txt",
            "https://tv.wekh.eu.org/itv.txt"
        ]

        # 打开文件以写入模式
        with open("tvlive/iptv.txt", "w") as file:
            for url in urls:
                try:
                    response = requests.get(url)
                    response.raise_for_status()  # 检查请求是否成功
                    playlist = response.text

                    # 不做任何替换或剔除，直接写入原始内容
                    if not playlist.endswith('\n'):
                        playlist += '\n'

                    file.write(playlist)
                    print(f"内容已成功从 {url} 保存到 tvlive/iptv.txt 文件中")

                except requests.exceptions.RequestException as e:
                    print(f"请求失败: {url} - {e}")

        print("所有内容已处理完毕")
        EOF

        python get_iptv.py

    - name: Commit 和 push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add tvlive/iptv.txt
        git commit -m "Update live streams playlist" --allow-empty
        git push
